setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

source("1 - Calculate Boat Effort.R")
rm(list = ls())
source("2 - Calculate Land Effort.R")
rm(list = ls())
source("3 - Create Combined Grid Effort.R")
rm(list = ls())
source("4 - Extract Boat Sightings.R")
rm(list = ls())
source("5 - Extract Land Sightings.R")
rm(list = ls())
source("6 - Create Combined Grid Sightings.R")
rm(list = ls())
source("7 - Calculate Encounter Rates.R")